name: LH Audits
on: [push]
jobs:
    run_lighthouse:
        runs-on: ec2
        timeout-minutes: 10
        steps:
            - name: Install Dependencies
              run: npm install;
            
            - name: Run Lighthouse CI
              run: |
                npm install -g @lhci/cli@0.6.x
                lhci autorun --disable-network-throttling --disable-cpu-throttling
              env:
                LHCI_GITHUB_TOKEN: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
            
            - name: Save lighthouse results
              if: always()
              uses: actions/upload-artifact@v2
              with:
                name: lighthouse-results
                path: .lighthouseci # This will save the lighthouse as .json files